name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download additional dependencies
      run: wget https://cdn.getbukkit.org/spigot/spigot-1.15.1.jar && mvn install:install-file -Dfile=spigot-1.15.1.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.15.1-R0.1-SNAPSHOT -Dpackaging=jar
    - name: Build with Maven
      run: mvn -B package --file pom.xml
